version: '3'

services:
  libsoundio:
    image: registry.chrz.de/public/libsoundio-builder:latest
    build: .
    volumes: 
      - ./libsoundio:/app/libsoundio:rw
      - ./build:/app/build:rw
          