version: '3'

services:
  libsoundio:
    image: stargate01/libsoundio-builder:latest
    build: .
    volumes: 
      - ./libsoundio:/app/libsoundio:rw
      - ./build:/app/build:rw
          