version: '3'

services:
  libsoundio:
    image: voiceamongus/libsoundio-builder:latest
    build: .
    volumes: 
      - ./libsoundio:/app/libsoundio:rw
      - ./build:/app/build:rw
          